use clap::Parser;
use morphogen_audio::StftConfig;
use morphogen_render::{
    CascadeFieldType, CascadeTrailSettings, CoagulationSettings, ConvolutionBlendSettings,
    DispersionSettings, FieldParticleSettings, FlowFeedbackSettings, FluidAdvectSettings,
    FluidAdvectTwoSourceSettings, FluidMosaicSettings, GranularMosaicSettings, StructureMode,
    VideoVocoderSettings,
};

mod args;
mod audio;
mod error;
mod imaging;
mod project;
mod queue;
mod render;
mod showcase;
use args::*;
use audio::*;
use error::CliError;
use project::*;
use queue::*;
use render::*;
use showcase::*;

fn main() {
    if let Err(error) = run() {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), CliError> {
    let cli = Cli::parse();

    match cli.command {
        Commands::InitExample { output_path } => init_example(&output_path),
        Commands::Probe { media_path } => probe(&media_path),
        Commands::ExtractFrames {
            input,
            output_dir,
            fps,
            max_frames,
        } => extract_frames(&input, &output_dir, fps, max_frames),
        Commands::ExtractAudio {
            input,
            output_wav,
            sample_rate,
            max_duration_seconds,
        } => extract_audio(&input, &output_wav, sample_rate, max_duration_seconds),
        Commands::ExportAudioStem {
            input_wav,
            output_wav,
            gain,
        } => export_audio_stem(&input_wav, &output_wav, gain),
        Commands::CacheStft {
            input_wav,
            output_json,
            fft_size,
            hop_size,
            window,
        } => cache_stft(&input_wav, &output_json, fft_size, hop_size, window.into()),
        Commands::CacheOnsets {
            input_wav,
            output_json,
            fft_size,
            hop_size,
            window,
        } => cache_onsets(&input_wav, &output_json, fft_size, hop_size, window.into()),
        Commands::CacheRms {
            input_wav,
            output_json,
            window_size,
            hop_size,
        } => cache_rms(&input_wav, &output_json, window_size, hop_size),
        Commands::RenderSpectralCrossSynth {
            modulator_wav,
            carrier_wav,
            output_wav,
            mode,
            amount,
            filter_type,
            rms_window,
            rms_hop,
            fft_size,
            stft_hop,
            window,
        } => render_spectral_cross_synth(
            &modulator_wav,
            &carrier_wav,
            &output_wav,
            mode,
            amount,
            filter_type.into(),
            rms_window,
            rms_hop,
            StftConfig {
                fft_size,
                hop_size: stft_hop,
                window: window.into(),
            },
        ),
        Commands::RenderAudioImpulseConvolution {
            modulator_wav,
            carrier_wav,
            output_wav,
            amount,
            max_impulse_samples,
            method,
            resample_impulse,
            ir_mode,
        } => render_audio_impulse_convolution(
            &modulator_wav,
            &carrier_wav,
            &output_wav,
            amount,
            max_impulse_samples,
            method.into(),
            resample_impulse,
            ir_mode.into(),
        ),
        Commands::RenderVideoAudioRoute {
            modulator_dir,
            carrier_wav,
            output_wav,
            descriptor,
            mode,
            filter_type,
            sampling,
            amount,
            fps,
            max_frames,
        } => render_video_audio_route(
            &modulator_dir,
            &carrier_wav,
            &output_wav,
            descriptor,
            mode,
            filter_type,
            sampling,
            amount,
            fps,
            max_frames,
        ),
        Commands::RenderTest { output_path } => render_test(&output_path),
        Commands::MetalRenderTest { output_path } => metal_render_test(&output_path),
        Commands::RenderTwoSource {
            modulator_image,
            carrier_image,
            output_path,
            amount,
            flow_cache_dir,
        } => render_two_source(
            &modulator_image,
            &carrier_image,
            &output_path,
            amount,
            flow_cache_dir.as_deref(),
        ),
        Commands::RenderGranularMosaic {
            modulator_image,
            carrier_image,
            output_path,
            grain_size,
            rearrangement,
            variation,
            seed,
            grain_cache_dir,
            backend,
            selection,
        } => render_granular_mosaic(
            &modulator_image,
            &carrier_image,
            &output_path,
            GranularMosaicSettings {
                grain_size,
                rearrangement,
                variation,
                seed,
            },
            grain_cache_dir.as_deref(),
            backend.into(),
            selection.into(),
        ),
        Commands::RenderGranularMosaicSequence {
            modulator_dir,
            carrier_dir,
            output_dir,
            grain_size,
            rearrangement,
            variation,
            seed,
            rms_cache,
            onset_cache,
            stft_cache,
            rms_variation_scale,
            onset_rearrangement_scale,
            centroid_grain_size_scale,
            frame_rate,
            max_frames,
            grain_cache_dir,
            backend,
            selection,
        } => render_granular_mosaic_sequence(GranularMosaicSequenceRenderRequest {
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_dir: &output_dir,
            settings: GranularMosaicSettings {
                grain_size,
                rearrangement,
                variation,
                seed,
            },
            frame_rate,
            max_frames,
            grain_cache_dir: grain_cache_dir.as_deref(),
            backend: backend.into(),
            audio_modulation: granular_audio_modulation_from_cli(
                rms_cache.as_deref(),
                onset_cache.as_deref(),
                stft_cache.as_deref(),
                rms_variation_scale,
                onset_rearrangement_scale,
                centroid_grain_size_scale,
            ),
            selection_mode: selection.into(),
        })
        .map(|_| ()),
        Commands::RenderVideoVocoder {
            modulator_image,
            carrier_image,
            output_path,
            bands,
            amount,
            mode,
            backend,
        } => render_video_vocoder(
            &modulator_image,
            &carrier_image,
            &output_path,
            VideoVocoderSettings { bands, amount },
            mode,
            backend.into(),
        ),
        Commands::RenderVideoVocoderSequence {
            modulator_dir,
            carrier_dir,
            output_dir,
            bands,
            amount,
            mode,
            backend,
            max_frames,
        } => render_video_vocoder_sequence(
            &modulator_dir,
            &carrier_dir,
            &output_dir,
            VideoVocoderSettings { bands, amount },
            mode,
            backend.into(),
            max_frames,
        )
        .map(|_| ()),
        Commands::RenderAudioVideoRouteSequence {
            modulator_wav,
            carrier_dir,
            output_dir,
            amount,
            shift_x,
            shift_y,
            rms_window,
            rms_hop,
            fps,
            backend,
            max_frames,
        } => render_audio_video_route_sequence(AudioVideoRouteSequenceRequest {
            modulator_wav: &modulator_wav,
            carrier_dir: &carrier_dir,
            output_dir: &output_dir,
            amount,
            shift_x,
            shift_y,
            rms_window,
            rms_hop,
            fps,
            backend: backend.into(),
            max_frames,
        })
        .map(|_| ()),
        Commands::RenderDatamoshSequence {
            modulator_dir,
            carrier_dir,
            output_dir,
            keyframe_interval,
            amount,
            block_size,
            residual_gain,
            residual_decay,
            block_refresh_threshold,
            vector_remix,
            remix_seed,
            preset,
            flow_cache_dir,
            backend,
            max_frames,
            stop_after_frame,
        } => render_datamosh_sequence(DatamoshSequenceRequest {
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_dir: &output_dir,
            flow_cache_dir: flow_cache_dir.as_deref(),
            keyframe_interval,
            amount,
            block_size,
            residual_gain,
            residual_decay,
            refresh_threshold: block_refresh_threshold,
            vector_remix: vector_remix.into(),
            remix_seed,
            preset: preset.into(),
            backend: backend.into(),
            max_frames,
            job_id: "direct-datamosh",
            provenance: None,
            stop_after_frame,
        })
        .map(|_| ()),
        Commands::DatamoshBitstream {
            input,
            output_dir,
            fps,
            operation,
            p_frame_index,
            duplicate_count,
            carrier,
            carrier_keyframes,
        } => datamosh_bitstream(DatamoshBitstreamRequest {
            input: &input,
            output_dir: &output_dir,
            fps,
            operation,
            p_frame_index,
            duplicate_count,
            carrier: carrier.as_deref(),
            carrier_keyframes,
        }),
        Commands::RenderConvolutionalBlendSequence {
            modulator_dir,
            carrier_dir,
            output_dir,
            kernel_size,
            amount,
            kernel_mode,
            backend,
            max_frames,
        } => render_convolutional_blend_sequence(ConvolutionalBlendSequenceRequest {
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_dir: &output_dir,
            settings: ConvolutionBlendSettings {
                kernel_size,
                amount,
            },
            kernel_mode: kernel_mode.into(),
            backend: backend.into(),
            max_frames,
        })
        .map(|_| ()),
        Commands::RenderDispersionBlendSequence {
            source_a_dir,
            source_b_dir,
            output_dir,
            block_size,
            color_weight,
            texture_weight,
            coagulation_strength,
            randomness,
            coherence_passes,
            coherence_strength,
            bias,
            ownership_refresh,
            coherent_amount,
            scatter_amount,
            damping,
            dispersion_ramp,
            smear,
            smear_decay,
            seed,
            max_frames,
        } => render_dispersion_blend_sequence(DispersionBlendSequenceRequest {
            source_a_dir: &source_a_dir,
            source_b_dir: &source_b_dir,
            output_dir: &output_dir,
            settings: DispersionSettings {
                block_size,
                color_weight,
                texture_weight,
                coagulation_strength,
                randomness,
                coherence_passes,
                coherence_strength,
                bias,
                coherent_amount,
                scatter_amount,
                damping,
                seed,
            },
            ownership_refresh,
            dispersion_ramp,
            smear,
            smear_decay,
            max_frames,
        })
        .map(|_| ()),
        Commands::RenderFluidAdvectSequence {
            source_dir,
            output_dir,
            frames,
            advect,
            turbulence_scale,
            turbulence_speed,
            detail,
            reinject,
            seed,
            backend,
        } => render_fluid_advect_sequence(FluidAdvectSequenceRequest {
            source_dir: &source_dir,
            output_dir: &output_dir,
            settings: FluidAdvectSettings {
                advect,
                turbulence_scale,
                turbulence_speed,
                detail,
                reinject,
                seed,
            },
            frames,
            backend: backend.into(),
        })
        .map(|_| ()),
        Commands::RenderFluidAdvectTwoSourceSequence {
            source_a_dir,
            source_b_dir,
            output_dir,
            frames,
            advect,
            reinject,
            backend,
        } => render_fluid_advect_two_source_sequence(FluidAdvectTwoSourceSequenceRequest {
            source_a_dir: &source_a_dir,
            source_b_dir: &source_b_dir,
            output_dir: &output_dir,
            settings: FluidAdvectTwoSourceSettings { advect, reinject },
            frames,
            backend: backend.into(),
        })
        .map(|_| ()),
        Commands::RenderOpticalFlowAdvectSequence {
            source_dir,
            output_dir,
            frames,
            advect,
            reinject,
            backend,
        } => render_optical_flow_advect_sequence(OpticalFlowAdvectSequenceRequest {
            source_dir: &source_dir,
            output_dir: &output_dir,
            settings: FluidAdvectTwoSourceSettings { advect, reinject },
            frames,
            backend: backend.into(),
        })
        .map(|_| ()),
        Commands::RenderFieldParticlesSequence {
            source_dir,
            output_dir,
            frames,
            spacing,
            particle_size,
            advect,
            turbulence_scale,
            turbulence_speed,
            detail,
            live_colour,
            seed,
            backend,
        } => render_field_particles_sequence(FieldParticlesSequenceRequest {
            source_dir: &source_dir,
            output_dir: &output_dir,
            settings: FieldParticleSettings {
                spacing,
                particle_size,
                advect,
                turbulence_scale,
                turbulence_speed,
                detail,
                live_color: live_colour,
                seed,
            },
            frames,
            backend: backend.into(),
        })
        .map(|_| ()),
        Commands::RenderCascadeTrailsSequence {
            source_dir,
            output_dir,
            frames,
            tile_size,
            grid_spacing,
            advect,
            turbulence_scale,
            detail,
            no_live_refresh,
            seed,
            field,
            river_direction,
            river_speed,
            river_turbulence,
        } => render_cascade_trails_sequence(CascadeTrailsSequenceRequest {
            source_dir: &source_dir,
            output_dir: &output_dir,
            settings: CascadeTrailSettings {
                tile_size,
                grid_spacing,
                advect,
                turbulence_scale,
                detail,
                live_refresh: !no_live_refresh,
                seed,
                field: match field {
                    args::CliCascadeFieldType::Vortex => CascadeFieldType::Vortex,
                    args::CliCascadeFieldType::River => CascadeFieldType::River,
                    args::CliCascadeFieldType::RiverRoot => CascadeFieldType::RiverRoot,
                },
                river_direction,
                river_speed,
                river_turbulence,
            },
            frames,
        })
        .map(|_| ()),
        Commands::RenderFluidMosaicSequence {
            source_a_dir,
            source_b_dir,
            output_dir,
            frames,
            tile_size,
            color_bins,
            cohesion,
            cohesion_radius,
            repulsion,
            repulsion_radius,
            fluid_strength,
            fluid_scale,
            fluid_drift,
            damping,
            settle_iterations,
            jitter,
            flat_tiles,
            adaptive_tiles,
            min_tile_size,
            subdivide_threshold,
            live_refresh,
            live_resort,
            cluster_blob,
            dispersion_band,
            band_width,
            band_speed,
            band_start,
            turbulence,
            turbulence_scale,
            turbulence_speed,
            vortex_flow,
            vortex_scale,
            vortex_detail,
            vortex_speed,
            seed,
        } => {
            // When the steady-vortex flow is active it is meant to be the dominant
            // current, so the analytic fluid + jitter (which otherwise read as a wobble
            // that masks it) default to off and the force balance defaults to the
            // coverage-preserving recipe (lower cohesion, stiffer/longer repulsion) so the
            // flowing tiles stay space-filling. Any flag passed explicitly still wins.
            let vortex_active = vortex_flow > 0.0;
            let cohesion = cohesion.unwrap_or(if vortex_active { 0.015 } else { 0.035 });
            let repulsion = repulsion.unwrap_or(if vortex_active { 3.0 } else { 1.4 });
            let repulsion_radius =
                repulsion_radius.unwrap_or(if vortex_active { 16.0 } else { 10.0 });
            let fluid_strength = fluid_strength.unwrap_or(if vortex_active { 0.0 } else { 0.5 });
            let jitter = jitter.unwrap_or(if vortex_active { 0.0 } else { 0.03 });
            render_fluid_mosaic_sequence(FluidMosaicSequenceRequest {
                source_a_dir: &source_a_dir,
                source_b_dir: &source_b_dir,
                output_dir: &output_dir,
                settings: FluidMosaicSettings {
                    tile_size,
                    color_bins,
                    cohesion,
                    cohesion_radius,
                    repulsion,
                    repulsion_radius,
                    fluid_strength,
                    fluid_scale,
                    fluid_drift,
                    damping,
                    settle_iterations,
                    jitter,
                    carry_texture: !flat_tiles,
                    adaptive_tiles,
                    min_tile_size,
                    subdivide_threshold,
                    live_refresh,
                    live_resort,
                    cluster_blob,
                    dispersion_band,
                    band_width,
                    band_speed,
                    band_start,
                    turbulence,
                    turbulence_scale,
                    turbulence_speed,
                    vortex_flow,
                    vortex_scale,
                    vortex_detail,
                    vortex_speed,
                    seed,
                },
                frames,
            })
            .map(|_| ())
        }
        Commands::RenderCoagulatedBlendSequence {
            source_a_dir,
            source_b_dir,
            output_dir,
            patch_size,
            color_weight,
            texture_weight,
            coherence_passes,
            coherence_strength,
            randomness,
            coagulation_strength,
            edge_hardness,
            edge_dither,
            block_jitter,
            bias,
            seed,
            advect_source,
            advect_amount,
            refresh,
            turbulence,
            smear,
            smear_decay,
            backend,
            max_frames,
        } => render_coagulated_blend_sequence(CoagulatedBlendSequenceRequest {
            source_a_dir: &source_a_dir,
            source_b_dir: &source_b_dir,
            output_dir: &output_dir,
            settings: CoagulationSettings {
                patch_size,
                color_weight,
                texture_weight,
                coherence_passes,
                coherence_strength,
                randomness,
                coagulation_strength,
                edge_hardness,
                edge_dither,
                block_jitter,
                bias,
                seed,
            },
            flow_source: advect_source.into(),
            advect_amount,
            refresh,
            turbulence,
            smear,
            smear_decay,
            backend: backend.into(),
            max_frames,
        })
        .map(|_| ()),
        Commands::RenderGranularMosaicPoolSequence {
            modulator_dir,
            carrier_dir,
            output_dir,
            grain_size,
            rearrangement,
            variation,
            seed,
            audio_weight,
            texture_weight,
            modulator_rms_cache,
            carrier_rms_cache,
            modulator_centroid_cache,
            carrier_centroid_cache,
            pool_window,
            anti_repeat_weight,
            anti_repeat_cooldown,
            coherence_weight,
            coherence_reach,
            spatial_coherence_weight,
            frame_rate,
            max_frames,
            grain_cache_dir,
            backend,
        } => render_granular_mosaic_pool_sequence(GranularMosaicPoolSequenceRequest {
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_dir: &output_dir,
            settings: GranularMosaicSettings {
                grain_size,
                rearrangement,
                variation,
                seed,
            },
            audio_weight,
            texture_weight,
            modulator_rms_cache: modulator_rms_cache.as_deref(),
            carrier_rms_cache: carrier_rms_cache.as_deref(),
            modulator_centroid_cache: modulator_centroid_cache.as_deref(),
            carrier_centroid_cache: carrier_centroid_cache.as_deref(),
            pool_window,
            anti_repeat_weight,
            anti_repeat_cooldown,
            coherence_weight,
            coherence_reach,
            spatial_coherence_weight,
            frame_rate,
            max_frames,
            grain_cache_dir: grain_cache_dir.as_deref(),
            backend: backend.into(),
        })
        .map(|_| ()),
        Commands::RenderFrameSequence {
            modulator_dir,
            carrier_dir,
            output_dir,
            amount,
            flow_cache_dir,
            max_frames,
            rms_modulator_wav,
            frame_rate,
            rms_window_size,
            rms_hop_size,
            rms_amount_scale,
            backend,
        } => render_frame_sequence(FrameSequenceRenderRequest {
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_dir: &output_dir,
            amount,
            flow_cache_dir: flow_cache_dir.as_deref(),
            max_frames,
            backend: backend.into(),
            rms: RmsAmountConfig {
                wav_path: rms_modulator_wav.as_deref(),
                frame_rate,
                window_size: rms_window_size,
                hop_size: rms_hop_size,
                amount_scale: rms_amount_scale,
            },
        })
        .map(|_| ()),
        Commands::RenderShowcase {
            modulator_dir,
            carrier_dir,
            output_dir,
            intensity,
            frames_per_effect,
            frame_rate,
            granular_grain_size,
            seed,
            backend,
            no_mp4,
        } => render_showcase(ShowcaseRenderRequest {
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_dir: &output_dir,
            intensity,
            frames_per_effect,
            frame_rate,
            granular_grain_size,
            seed,
            backend: backend.into(),
            encode_mp4: !no_mp4,
        }),
        Commands::RenderFeedbackSequence {
            modulator_dir,
            carrier_dir,
            output_dir,
            carrier_amount,
            feedback_amount,
            feedback_mix,
            decay,
            iterations,
            structure_mix,
            structure_mode,
            output_bit_depth,
            temporal_supersampling,
            flow_cache_dir,
            max_frames,
            reset_at_frame,
            frame_rate,
            backend,
            flow_source,
            stop_after_frame,
        } => render_feedback_sequence(FeedbackSequenceRenderRequest {
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_dir: &output_dir,
            flow_cache_dir: flow_cache_dir.as_deref(),
            max_frames,
            reset_at_frame,
            frame_rate,
            settings: FlowFeedbackSettings {
                carrier_amount,
                feedback_amount,
                feedback_mix,
                decay,
                iterations,
                structure_mix,
                structure_mode: structure_mode.into(),
            },
            output_bit_depth,
            temporal_supersampling,
            backend: backend.into(),
            flow_source: flow_source.into(),
            job_id: "direct-feedback-sequence",
            provenance: None,
            stop_after_frame,
        })
        .map(|_| ()),
        Commands::CacheSyntheticFlow {
            output_dir,
            width,
            height,
        } => cache_synthetic_flow(&output_dir, width, height),
        Commands::CacheLuminanceFlow {
            modulator_image,
            output_dir,
            width,
            height,
        } => cache_luminance_flow(&modulator_image, &output_dir, width, height),
        Commands::QueueInit { queue_path } => queue_init(&queue_path),
        Commands::QueueAddTest {
            queue_path,
            project_path,
        } => queue_add_test(&queue_path, project_path.as_deref()),
        Commands::QueueAddFrameSequence {
            queue_path,
            modulator_dir,
            carrier_dir,
            output_root_dir,
            amount,
            max_frames,
            frame_rate,
            no_flow_cache,
            backend,
            project_path,
        } => queue_add_frame_sequence(QueueAddFrameSequenceRequest {
            queue_path: &queue_path,
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_root_dir: &output_root_dir,
            amount,
            max_frames,
            frame_rate,
            write_flow_cache: !no_flow_cache,
            backend: backend.into(),
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddFeedbackSequence {
            queue_path,
            modulator_dir,
            carrier_dir,
            output_root_dir,
            carrier_amount,
            feedback_amount,
            feedback_mix,
            decay,
            iterations,
            structure_mix,
            output_bit_depth,
            temporal_supersampling,
            max_frames,
            reset_at_frame,
            frame_rate,
            no_flow_cache,
            backend,
            flow_source,
            project_path,
        } => queue_add_feedback_sequence(QueueAddFeedbackSequenceRequest {
            queue_path: &queue_path,
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_root_dir: &output_root_dir,
            settings: FlowFeedbackSettings {
                carrier_amount,
                feedback_amount,
                feedback_mix,
                decay,
                iterations,
                structure_mix,
                // Multiscale structure mode is exposed only on the direct CPU
                // render path for now; the persisted queue keeps single-scale
                // (backlog: Structure-Preserving Morph task 5 follow-up).
                structure_mode: StructureMode::SingleScale,
            },
            output_bit_depth,
            temporal_supersampling,
            max_frames,
            reset_at_frame,
            frame_rate,
            write_flow_cache: !no_flow_cache,
            backend: backend.into(),
            flow_source: flow_source.into(),
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddFluidAdvectSequence {
            queue_path,
            source_dir,
            output_root_dir,
            frames,
            frame_rate,
            advect,
            turbulence_scale,
            turbulence_speed,
            detail,
            reinject,
            seed,
            backend,
            project_path,
        } => queue_add_fluid_advect_sequence(QueueAddFluidAdvectSequenceRequest {
            queue_path: &queue_path,
            source_dir: &source_dir,
            output_root_dir: &output_root_dir,
            settings: FluidAdvectSettings {
                advect,
                turbulence_scale,
                turbulence_speed,
                detail,
                reinject,
                seed,
            },
            frames,
            frame_rate,
            backend: backend.into(),
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddFluidAdvectTwoSourceSequence {
            queue_path,
            source_a_dir,
            source_b_dir,
            output_root_dir,
            frames,
            frame_rate,
            advect,
            reinject,
            backend,
            project_path,
        } => queue_add_fluid_advect_two_source_sequence(
            QueueAddFluidAdvectTwoSourceSequenceRequest {
                queue_path: &queue_path,
                source_a_dir: &source_a_dir,
                source_b_dir: &source_b_dir,
                output_root_dir: &output_root_dir,
                settings: FluidAdvectTwoSourceSettings { advect, reinject },
                frames,
                frame_rate,
                backend: backend.into(),
                project_path: project_path.as_deref(),
            },
        ),
        Commands::QueueAddOpticalFlowAdvectSequence {
            queue_path,
            source_dir,
            output_root_dir,
            frames,
            frame_rate,
            advect,
            reinject,
            backend,
            project_path,
        } => queue_add_optical_flow_advect_sequence(QueueAddOpticalFlowAdvectSequenceRequest {
            queue_path: &queue_path,
            source_dir: &source_dir,
            output_root_dir: &output_root_dir,
            settings: FluidAdvectTwoSourceSettings { advect, reinject },
            frames,
            frame_rate,
            backend: backend.into(),
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddFieldParticlesSequence {
            queue_path,
            source_dir,
            output_root_dir,
            frames,
            frame_rate,
            spacing,
            particle_size,
            advect,
            turbulence_scale,
            turbulence_speed,
            detail,
            live_colour,
            seed,
            backend,
            project_path,
        } => queue_add_field_particles_sequence(QueueAddFieldParticlesSequenceRequest {
            queue_path: &queue_path,
            source_dir: &source_dir,
            output_root_dir: &output_root_dir,
            settings: FieldParticleSettings {
                spacing,
                particle_size,
                advect,
                turbulence_scale,
                turbulence_speed,
                detail,
                live_color: live_colour,
                seed,
            },
            frames,
            frame_rate,
            backend: backend.into(),
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddCascadeTrailsSequence {
            queue_path,
            source_dir,
            output_root_dir,
            frames,
            frame_rate,
            tile_size,
            grid_spacing,
            advect,
            turbulence_scale,
            detail,
            no_live_refresh,
            seed,
            field,
            river_direction,
            river_speed,
            river_turbulence,
            project_path,
        } => queue_add_cascade_trails_sequence(QueueAddCascadeTrailsSequenceRequest {
            queue_path: &queue_path,
            source_dir: &source_dir,
            output_root_dir: &output_root_dir,
            settings: CascadeTrailSettings {
                tile_size,
                grid_spacing,
                advect,
                turbulence_scale,
                detail,
                live_refresh: !no_live_refresh,
                seed,
                field: match field {
                    args::CliCascadeFieldType::Vortex => CascadeFieldType::Vortex,
                    args::CliCascadeFieldType::River => CascadeFieldType::River,
                    args::CliCascadeFieldType::RiverRoot => CascadeFieldType::RiverRoot,
                },
                river_direction,
                river_speed,
                river_turbulence,
            },
            frames,
            frame_rate,
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddGranularMosaicSequence {
            queue_path,
            modulator_dir,
            carrier_dir,
            output_root_dir,
            grain_size,
            rearrangement,
            variation,
            seed,
            rms_cache,
            onset_cache,
            stft_cache,
            rms_variation_scale,
            onset_rearrangement_scale,
            centroid_grain_size_scale,
            max_frames,
            frame_rate,
            no_grain_cache,
            project_path,
            backend,
            selection,
        } => queue_add_granular_mosaic_sequence(QueueAddGranularMosaicSequenceRequest {
            queue_path: &queue_path,
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_root_dir: &output_root_dir,
            settings: GranularMosaicSettings {
                grain_size,
                rearrangement,
                variation,
                seed,
            },
            audio_modulation: granular_audio_modulation_from_cli(
                rms_cache.as_deref(),
                onset_cache.as_deref(),
                stft_cache.as_deref(),
                rms_variation_scale,
                onset_rearrangement_scale,
                centroid_grain_size_scale,
            ),
            max_frames,
            frame_rate,
            write_grain_cache: !no_grain_cache,
            project_path: project_path.as_deref(),
            backend: backend.into(),
            selection_mode: selection.into(),
        }),
        Commands::QueueAddGranularMosaicPoolSequence {
            queue_path,
            modulator_dir,
            carrier_dir,
            output_root_dir,
            grain_size,
            rearrangement,
            variation,
            seed,
            audio_weight,
            texture_weight,
            modulator_rms_cache,
            carrier_rms_cache,
            modulator_centroid_cache,
            carrier_centroid_cache,
            pool_window,
            anti_repeat_weight,
            anti_repeat_cooldown,
            coherence_weight,
            coherence_reach,
            spatial_coherence_weight,
            max_frames,
            frame_rate,
            no_grain_cache,
            project_path,
            backend,
        } => queue_add_granular_mosaic_pool_sequence(QueueAddGranularMosaicPoolSequenceRequest {
            queue_path: &queue_path,
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_root_dir: &output_root_dir,
            settings: GranularMosaicSettings {
                grain_size,
                rearrangement,
                variation,
                seed,
            },
            audio_weight,
            texture_weight,
            modulator_rms_cache: modulator_rms_cache.as_deref(),
            carrier_rms_cache: carrier_rms_cache.as_deref(),
            modulator_centroid_cache: modulator_centroid_cache.as_deref(),
            carrier_centroid_cache: carrier_centroid_cache.as_deref(),
            pool_window,
            anti_repeat_weight,
            anti_repeat_cooldown,
            coherence_weight,
            coherence_reach,
            spatial_coherence_weight,
            max_frames,
            frame_rate,
            write_grain_cache: !no_grain_cache,
            project_path: project_path.as_deref(),
            backend: backend.into(),
        }),
        Commands::QueueAddVideoVocoderSequence {
            queue_path,
            modulator_dir,
            carrier_dir,
            output_root_dir,
            bands,
            amount,
            mode,
            max_frames,
            frame_rate,
            project_path,
            backend,
        } => queue_add_video_vocoder_sequence(QueueAddVideoVocoderSequenceRequest {
            queue_path: &queue_path,
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_root_dir: &output_root_dir,
            settings: VideoVocoderSettings { bands, amount },
            mode: mode.into(),
            max_frames,
            frame_rate,
            project_path: project_path.as_deref(),
            backend: backend.into(),
        }),
        Commands::QueueAddSpectralCrossSynth {
            queue_path,
            modulator_wav,
            carrier_wav,
            output_root_dir,
            mode,
            amount,
            filter_type,
            rms_window,
            rms_hop,
            fft_size,
            stft_hop,
            window,
            project_path,
        } => queue_add_spectral_cross_synth(QueueAddSpectralCrossSynthRequest {
            queue_path: &queue_path,
            modulator_wav: &modulator_wav,
            carrier_wav: &carrier_wav,
            output_root_dir: &output_root_dir,
            mode: mode.into(),
            amount,
            filter_type: filter_type.into(),
            rms_window,
            rms_hop,
            fft_size,
            stft_hop,
            window: window.into(),
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddAudioImpulseConvolution {
            queue_path,
            modulator_wav,
            carrier_wav,
            output_root_dir,
            amount,
            max_impulse_samples,
            method,
            resample_impulse,
            ir_mode,
            project_path,
        } => queue_add_audio_impulse_convolution(QueueAddAudioImpulseConvolutionRequest {
            queue_path: &queue_path,
            modulator_wav: &modulator_wav,
            carrier_wav: &carrier_wav,
            output_root_dir: &output_root_dir,
            amount,
            max_impulse_samples,
            method: method.into(),
            resample_impulse,
            ir_mode: ir_mode.into(),
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddVideoAudioRoute {
            queue_path,
            modulator_dir,
            carrier_wav,
            output_root_dir,
            descriptor,
            mode,
            filter_type,
            sampling,
            amount,
            fps,
            project_path,
        } => queue_add_video_audio_route(QueueAddVideoAudioRouteRequest {
            queue_path: &queue_path,
            modulator_dir: &modulator_dir,
            carrier_wav: &carrier_wav,
            output_root_dir: &output_root_dir,
            descriptor: descriptor.into(),
            mode: mode.into(),
            filter_type: filter_type.into(),
            sampling: sampling.into(),
            amount,
            fps,
            project_path: project_path.as_deref(),
        }),
        Commands::QueueAddAudioVideoRouteSequence {
            queue_path,
            modulator_wav,
            carrier_dir,
            output_root_dir,
            amount,
            shift_x,
            shift_y,
            rms_window,
            rms_hop,
            frame_rate,
            max_frames,
            project_path,
            backend,
        } => queue_add_audio_video_route_sequence(QueueAddAudioVideoRouteSequenceRequest {
            queue_path: &queue_path,
            modulator_wav: &modulator_wav,
            carrier_dir: &carrier_dir,
            output_root_dir: &output_root_dir,
            amount,
            shift_x,
            shift_y,
            rms_window,
            rms_hop,
            frame_rate,
            max_frames,
            project_path: project_path.as_deref(),
            backend: backend.into(),
        }),
        Commands::QueueAddDatamoshSequence {
            queue_path,
            modulator_dir,
            carrier_dir,
            output_root_dir,
            keyframe_interval,
            amount,
            block_size,
            residual_gain,
            residual_decay,
            block_refresh_threshold,
            vector_remix,
            remix_seed,
            preset,
            flow_cache_dir,
            max_frames,
            project_path,
            backend,
        } => queue_add_datamosh_sequence(QueueAddDatamoshSequenceRequest {
            queue_path: &queue_path,
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_root_dir: &output_root_dir,
            keyframe_interval,
            amount,
            block_size,
            residual_gain,
            residual_decay,
            refresh_threshold: block_refresh_threshold,
            vector_remix: vector_remix.into(),
            remix_seed,
            preset: preset.into(),
            flow_cache_dir: flow_cache_dir.as_deref(),
            max_frames,
            project_path: project_path.as_deref(),
            backend: backend.into(),
        }),
        Commands::QueueRunDatamoshSequence { queue_path } => {
            queue_run_datamosh_sequence(&queue_path)
        }
        Commands::QueueAddDatamoshBitstream {
            queue_path,
            input_video,
            output_root_dir,
            fps,
            operation,
            p_frame_index,
            duplicate_count,
            carrier_video,
            carrier_keyframes,
            preset,
            project_path,
        } => queue_add_datamosh_bitstream(QueueAddDatamoshBitstreamRequest {
            queue_path: &queue_path,
            input_video: &input_video,
            output_root_dir: &output_root_dir,
            fps,
            operation: operation.into(),
            p_frame_index,
            duplicate_count,
            carrier_video: carrier_video.as_deref(),
            carrier_keyframes,
            preset: preset.into(),
            project_path: project_path.as_deref(),
        }),
        Commands::QueueRunDatamoshBitstream { queue_path } => {
            queue_run_datamosh_bitstream(&queue_path)
        }
        Commands::QueueAddConvolutionalBlendSequence {
            queue_path,
            modulator_dir,
            carrier_dir,
            output_root_dir,
            kernel_size,
            amount,
            kernel_mode,
            max_frames,
            project_path,
            backend,
        } => queue_add_convolutional_blend_sequence(QueueAddConvolutionalBlendSequenceRequest {
            queue_path: &queue_path,
            modulator_dir: &modulator_dir,
            carrier_dir: &carrier_dir,
            output_root_dir: &output_root_dir,
            settings: ConvolutionBlendSettings {
                kernel_size,
                amount,
            },
            kernel_mode: kernel_mode.into(),
            max_frames,
            project_path: project_path.as_deref(),
            backend: backend.into(),
        }),
        Commands::QueueRunConvolutionalBlendSequence { queue_path } => {
            queue_run_convolutional_blend_sequence(&queue_path)
        }
        Commands::QueueRunTest {
            queue_path,
            output_dir,
            stop_after_frame,
        } => queue_run_test(&queue_path, &output_dir, stop_after_frame),
        Commands::QueueRunFrameSequence { queue_path } => queue_run_frame_sequence(&queue_path),
        Commands::QueueRunFeedbackSequence { queue_path } => {
            queue_run_feedback_sequence(&queue_path)
        }
        Commands::QueueRunFluidAdvectSequence { queue_path } => {
            queue_run_fluid_advect_sequence(&queue_path)
        }
        Commands::QueueRunFluidAdvectTwoSourceSequence { queue_path } => {
            queue_run_fluid_advect_two_source_sequence(&queue_path)
        }
        Commands::QueueRunOpticalFlowAdvectSequence { queue_path } => {
            queue_run_optical_flow_advect_sequence(&queue_path)
        }
        Commands::QueueRunFieldParticlesSequence { queue_path } => {
            queue_run_field_particles_sequence(&queue_path)
        }
        Commands::QueueRunCascadeTrailsSequence { queue_path } => {
            queue_run_cascade_trails_sequence(&queue_path)
        }
        Commands::QueueRunGranularMosaicSequence { queue_path } => {
            queue_run_granular_mosaic_sequence(&queue_path)
        }
        Commands::QueueRunGranularMosaicPoolSequence { queue_path } => {
            queue_run_granular_mosaic_pool_sequence(&queue_path)
        }
        Commands::QueueRunVideoVocoderSequence { queue_path } => {
            queue_run_video_vocoder_sequence(&queue_path)
        }
        Commands::QueueRunSpectralCrossSynth { queue_path } => {
            queue_run_spectral_cross_synth(&queue_path)
        }
        Commands::QueueRunAudioImpulseConvolution { queue_path } => {
            queue_run_audio_impulse_convolution(&queue_path)
        }
        Commands::QueueRunVideoAudioRoute { queue_path } => {
            queue_run_video_audio_route(&queue_path)
        }
        Commands::QueueRunAudioVideoRouteSequence { queue_path } => {
            queue_run_audio_video_route_sequence(&queue_path)
        }
        Commands::QueueCancel { queue_path, job_id } => queue_cancel(&queue_path, &job_id),
        Commands::QueueInspect { queue_path } => queue_inspect(&queue_path),
        Commands::InspectProject { project_path } => inspect_project(&project_path),
        Commands::ProjectRegisterProxy {
            project_path,
            source_id,
            source_role,
            frame_dir,
            audio,
            analysis_cache,
        } => project_register_proxy(ProjectRegisterProxyRequest {
            project_path: &project_path,
            source_id: source_id.as_deref(),
            source_role: source_role.map(Into::into),
            frame_dir: &frame_dir,
            audio: audio.as_deref(),
            analysis_cache: &analysis_cache,
        }),
    }
}
